#!/usr/bin/bash

set -e  # exit script if a command fails

sudo apt-get -y update

sudo apt-get install -y fzf btop curl
go install github.com/air-verse/air@latest
sudo apt-get install -y git ripgrep xclip jq tldr python3-pip

# sudo apt-get install -y ghostty
# curl -sSfL https://get.tur.so/install.sh | bash

